
Vagrant.configure("2") do |config|
 
  config.vm.define "lemp"
  config.vm.hostname = "lemp"
  config.vm.box = "damianlewis/ubuntu-16.04-lemp"



  config.vm.synced_folder ".", "/var/www/html", :owner => 'www-data', :group => 'www-data'
  config.vm.synced_folder "./vagrant_example/nginx", "/etc/nginx/sites-available", :owner => 'root', :group => 'root'

  # 
  #
  config.vm.provider "virtualbox" do |vb|
 
    vb.memory = "2048"
  end
  #


  config.vm.provision "shell",
    inline: "service nginx start", run: "always"
  #   
end
